name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

      - name: Test with Maven
        run: mvn test

      - name: Publish to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # tidak diperlukan untuk repositori publik
          file: ./target/site/jacoco/jacoco.xml # jalur relatif ke file laporan Anda
          flags: unittests # opsional, flags memungkinkan Anda membedakan antara laporan coverage
          name: codecov-umbrella # opsional, namanya harus unik untuk menghindari konflik
          fail_ci_if_error: true # opsional (default = false), jika true CI akan gagal ketika Codecov mengalami kesalahan

